### PR TITLE
Add Timeserver fast-forward defense

### PR DESCRIPTION
**Pull request by awwad**
Addresses Issue #31.  Please see that for some additional background.

In short, the fast forward attack using the Time Server is a DoS attack in which an attacker who has compromised the Time Server key distributes times that are in the distant future, preventing any metadata from being verified even after the attack ends.

The defense is to allow Director Root metadata to rotate Time Server keys for full verification ECUs and Director Targets metadata to rotate Time Server keys for partial verification ECUs.

I am sure that some decisions that have been made here that are worth contemplating.  For example:
- "MAY" for inclusion of Time Server key in Root and Targets in the circumstances in which they are each useful (timeserver use, partial verification ECU use).  You could argue that this "MAY" should be a "MUST" (in those circumstances).  My thinking on the "MAY" is that the system works whether the key is always included or if the key is only included when it is updated (and the ECU stores it separately).  It might be better for consistency to treat this like a TUF role (always expecting it to be listed in the most recent metadata).

### CODE REVIEW

**Comment by awwad** [comment]
Draft of the updates to the spec

**Comment by awwad** [comment]
@tkfu, does this make sense to you?

**Comment by tkfu** [comment]
@awwad LGTM for content. I just changed the form a little bit, to harmonize the way we describe the metadata. (For the rest of the metadata fields, we describe what their contents should be in bulleted lists, so I think it makes more sense to describe the time server pubkey metadata in the same way.)

**Comment by tkfu** [comment]
@awwad Sorry, I just read your comment on why you went for MAY/SHOULD, and I changed it to CONDITIONALLY REQUIRED without addressing that. Let me explain my reasoning: there's no real advantage to implementing a system that includes the key only sometimes--the only difference is saving a couple of bytes on metadata transmission.

**Comment by awwad** [comment]
> @awwad Sorry, I just read your comment on why you went for MAY/SHOULD, and I changed it to CONDITIONALLY REQUIRED without addressing that. Let me explain my reasoning: there's no real advantage to implementing a system that includes the key only sometimes--the only difference is saving a couple of bytes on metadata transmission.

Good improvements, thanks!  Conditionally required seems to be the consensus. 😃

**Pull request merged**
