### PR TITLE
Clarify that installation steps are the same for primary and secondary. Fixes #44

### LINKED ISSUE #44: Updating primary
According to the section "Downloading and distributing updates on a primary ECU" the primary will never be updated.  This is probably not what is intended. :-)

### PR DESCRIPTION
**Pull request by JosiahOne**
This PR renames the "Downloading and Distributing Updates on a Primary ECU" section to "What the primary does" to make it clear that installation is not part of that section's scope.

I also renamed "Installing Images on ECUs" to "Installing Images on primary or secondary ECUs" to drive home that the *installation* steps for both ECU types are covered in that section. This change might not be necessary, though, and I welcome feedback.

### CODE REVIEW

**Comment by JosiahOne** [comment]
Cc @JustinCappos / @tkfu for review.

**Comment by JosiahOne** [comment]
@tkfu I can, though GitHub allows you to do this automatically when you merge by choosing "Squash and Merge" (or whatever).

**Comment by JosiahOne** [comment]
Here's what I'm referring to: https://github.blog/2016-09-26-rebase-and-merge-pull-requests/

Hopefully that approach is acceptable. I won't have the ability to rebase manually until tonight.

**Comment by tkfu** [comment]
Forgot about that option, thanks!

**Pull request merged**
