### PR TITLE
Add vehicle identifier to director targets metadata

### PR DESCRIPTION
**Pull request by mnm678**
Addresses part of #202.

The SHOULD in this pr should become a MUST in 2.0.0.

### CODE REVIEW

**Comment by jhdalek55** [comment]
Can we get another approval on this? And then re-post the 2.0.0 version of this?

**Comment by iramcdonald** [comment]
Hi,

Reviewed the whole discussion thread again, as well as Marina's suggested
text for v1.2.0 (w/ a SHOULD
for VIN in targets metadata).  I approve of this proposed text.

Cheers,
- Ira

**Comment by jhdalek55** [comment]
Please merge and then re-post the issue for 2.0.0

**Comment by jhdalek55** [comment]
@tkfu @JustinCappos  Can someone please merge this PR and repost the larger issue for 2.0.0?

**Review by tkfu — APPROVED** [review]

**Pull request merged**
