### PR TITLE
Make slow retrieval attack prevention a SHALL

### LINKED ISSUE #194: Make slow retrieval attack prevention a SHALL
In #193, we added a check for slow retrieval attacks to the standard. During discussion in that pr, we decided that this protection should be a SHALL in a future version of the standard.

### PR DESCRIPTION
**Pull request by mnm678**
Resolves #194

### CODE REVIEW

**Comment by jhdalek55** [comment]
Reviews please...@trishankkarthik @JustinCappos @tkfu

**Comment by jhdalek55** [comment]
@tkfu @trishankatdatadog  can we get this approved? It's just a wording change.

**Review by pattivacek — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
Hmm, nothing against this PR, but generally speaking, we should get >= 2 reviews from 2 different orgs to approve and merge going forward, no? 🙂

**Comment by iramcdonald** [comment]
Hi Trishank,

Yes and no.

In this instance, the bi-weekly Uptane Standards calls have had a strong
consensus for many
months that the Slow Retrieval Attack prevention should be a SHALL in
Uptane v2.0 (which is
allowed not to be completely backward compatible).

There's no need for a lot of new text.  In our bi-weekly discussions, our
consensus all along
has been that the lack of that SHALL was actually a bug in Uptane Standard
v1.x.

OTOH, I agree with you that reviews by >=2 people should be the mechanism
when there is
any significant new text added to the Standard or Deployment Considerations.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by trishankatdatadog** [comment]
> Hi Trishank, Yes and no. In this instance, the bi-weekly Uptane Standards calls have had a strong consensus for many months that the Slow Retrieval Attack prevention should be a SHALL in Uptane v2.0 (which is allowed not to be completely backward compatible). There's no need for a lot of new text. In our bi-weekly discussions, our consensus all along has been that the lack of that SHALL was actually a bug in Uptane Standard v1.x.

Ah, my bad, missed this context.

> OTOH, I agree with you that reviews by >=2 people should be the mechanism when there is any significant new text added to the Standard or Deployment Considerations. 

Should we make this the default threshold, going fwd? Unfortunately, I don't think there's any way to enforce a different number per review.

**Pull request merged**
