### PR TITLE
Adding Scudo reference--addresses Issue #222

### PR DESCRIPTION
**Pull request by jhdalek55**
I combined a few responses in this addition, one that Justin had left in the thread and another I jotted down from discussions at our 3/14 Standards meeting. Let me know if it makes sense

### CODE REVIEW

**Comment by iramcdonald** [comment]
Hi Lois,

Having just read the changed text, I find the following excerpt kind of obscure and actually informal:

"that may transition to a more formal mention as an Uptane Deployment Best Practice at some point. "

I suggest changing it to:

"that could be adopted as a formal recommendation in the Uptane Deployment Best Practices in the future"

**Comment by jhdalek55** [comment]
I like your suggestion @iramcdonald and will amend the pull request accordngly.

**Comment by jhdalek55** [comment]
Can we get reviews/approvals for this. It's a fairly simple fix and would allow us to close out Issue #222

**Review by mnm678 — APPROVED** [review]

**Comment by jhdalek55** [comment]
Second request for a second approval and a merger please. This is a small change but it will enable us to close another issue for V.2.1.0

**Comment by iramcdonald** [comment]
Hi Lois,

I approve.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Can someone who has permissions merge this PR?

**Review by mnm678 — APPROVED** [review]

**Pull request merged**
