### PR TITLE
Issue # 55 Data structures and profiles

### PR DESCRIPTION
**Pull request by OTAINFO**
Sorry for the delay. Please review for issue # 55. The changes I submitted starts from
Data tables & sample data structures ( line 1014).

### CODE REVIEW

**Comment by patrickvacek** [comment]
@OTAINFO I'm a bit confused by what I'm looking at. It looks like you have made a lot more changes than what you mentioned, and they conflict with the current version. You might need to rebase your branch or double-check that you've included what you meant to for this specific change.

**Comment by OTAINFO** [comment]
Let me try rebasing my branch.

**Comment by OTAINFO** [comment]
Following: https://help.github.com/en/articles/syncing-a-fork
I dont have rights to sync up with upstream. 
 git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by OTAINFO** [comment]
Following: https://help.github.com/en/articles/syncing-a-fork
I dont have rights to sync up with upstream. 
 git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by tkfu** [comment]
Hi Akshay,

Please re-read the first sentence of the article you linked:

> Before you can sync your fork with an upstream repository, you must [configure a remote that points to the upstream repository](https://help.github.com/en/articles/configuring-a-remote-for-a-fork) in Git.

**Comment by OTAINFO** [comment]
Yes I already did it and I am not blocked now. 
Thanks,
Akshay

**Comment by tkfu** [comment]
Okay, I've looked at the section you've added now, and this is a very, very long way from being mergeable.

There are at least three basic problems that should be fairly straightforward to fix:

1. Your branch does not render; this is due to syntax errors. You can use the makefile and the instructions in the readme to verify that it works. There are also some problems with the markdown/syntax that will need to be fixed later, but the first step is to at least create a file that can be rendered.
2. You've included lengthy json examples. These do not belong in the standard; json and ASN1 examples will be included in the deployment considerations doc.
3. It would appear that you took an old clone of the repo, cut-and-pasted a newer version of the markdown file, added your changes, then committed the whole thing. That won't work, and can't be fixed with rebasing. You'll need to sync your master branch with upstream, then add your changes based on that, then either do an amend commit or squash your previous erroneous commit.

But on a higher level, this PR doesn't address #55 as discussed in that thread, and it contains numerous, numerous errors. I'm sorry to be so blunt, but I don't think that we should attempt to review and fix all of the issues here; it would be much faster for someone else to start from scratch.

I'm not going to close this right away, just in case other contributors have a different evaluation or are willing to try to fix/review this, but if there hasn't been any movement on it before our next meeting I'll ask for a different volunteer to take a crack at it.

**Comment by OTAINFO** [comment]
Thanks for the headsup. Sure, someone can take over. 
Thanks
Alshay

**Pull request closed without merging**
