### PR TITLE
Removing the word "private" from Section 5.4.1

### PR DESCRIPTION
**Pull request by jhdalek55**
This removes the word "private" in section 5.4.1 to reduce confusion as discussed in Issue #174 and new Issue # 241. A fuller description of the various types of keys used by Uptane should be added to the Deployment Best Practices page as well.

### CODE REVIEW

**Comment by jhdalek55** [comment]
Note, as per our discussion at the 10/11 Uptane Standards meeting, this wraps up the "semantic" fixes raised in Issue #174. Issue #241 maintains the central question of #174, without many of the side issues that evolved in that discussion.

**Review by pattivacek — APPROVED** [review]

**Comment by jhdalek55** [comment]
Can we get a second approval on this so we can merge?

**Review by JustinCappos — APPROVED** [review]

**Comment by jhdalek55** [comment]
@mnm678 can you merge this for me? I has two approving reviews.

**Comment by jhdalek55** [comment]
Thanks @pattivacek ...

**Pull request merged**
