### PR TITLE
Remove HW IDs from custom targets metadata

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Related to #33, please review carefully, thanks

Cc @cajun-rat

### CODE REVIEW

**Comment by cajun-rat** [comment]
Dropping Hardware IDs is quite a big change to the spec--in the ATS/HERE implementation they are the primary method for restricting which ECUs can install which updates. I'll let @patrickvacek, @OYTIS and @tkfu comment on the backwards compatibility question, but isn't this is change is effectively reversing the roles of Hardware Id and image name?

I guess there is some context from the F2F meeting I'm missing here, but it would be good to understand the reasoning.

**Comment by iramcdonald** [comment]
Hi,

There was certainly no discussion during last Friday's workshop of
abandoning support for Hardware IDs associated with images.

I'm confused about why this change is being suggested.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by OYTIS** [comment]
@cajun-rat Thank you for mentioning me.

I could not attend to Friday workshop (not quite sure I'm still eligible to), so I'm not quite sure what the intention was. In my view hardware identifiers in **director's** target metadata is strictly required even from the functional point of view, otherwise it's not clear what image belongs to what ECU. As for images/delegations, omitting the hardware ID there would enable an attacker to brick ECUs provided that director is compromised. Hardware-scoped delegations could protect from that, but only if every delegation is assigned exactly one hardware ID.

**Comment by trishankatdatadog** [comment]
Everyone: this PR is _not_ dropping hardware identifiers (HW IDs) from the spec.

Previously, HW IDs were noted only in the custom targets metadata. Now, it's being listed in delegations themselves.

What this PR is doing is dropping HW IDs from custom targets metadata, so that they are listed and observed only from delegations instead.

This way, we don't have two redundant mechanisms for doing the same thing. Does this make sense?

**Comment by OYTIS** [comment]
Sorry, don't quite get it. I would imagine that if a delegation supports hardware IDs A, B and C it doesn't mean that all images listed in the delegation support all these three platform. Rather it would mean that some of the targets are for A, others are for B and others are for C. We probably don't want to lose this information.
Am I missing something?

**Comment by trishankatdatadog** [comment]
@OYTIS Good question. You can use further delegations to narrow down exactly which roles are trusted for which HW IDs.

My thinking is that using two different sources of information for HW IDs will lead to unnecessary redundancy, if not mistakes.

**Comment by tkfu** [comment]
There’s still the issue that the director fundamentally needs to specify hardwareIDs: its raison d’être is to **direct** particular ECUs to install particular images. If hardwareIDs are in delegations, it can’t do that.

Secondly, I think confuses the purpose of delegations even further. They’re no longer an optional way to delegate authority; they’re a required element, and a new delegation has to be created for each possible hardware variant.

But more fundamentally, I think this creates quite a lot more unnecessary complexity (and indeed redundancy) than it saves.

**Comment by OYTIS** [comment]
@trishankatdatadog

Good point. These two pieces of metadata can indeed be inconsistent. IMO, it's not too bad, because thar could only lead to denial of this particular update, which is a fair response to an operator error.

I'm not sure that avoiding that mistake is worth putting such strict restrictions on the delegation tree. More than that: a delegation tree constructed that way will contain redundant information and will enable mistake. That is, putting a delegation for HW C under a delegation for HW [A, B] is not that different from putting a target for HW C under the same delegation.

**Comment by trishankatdatadog** [comment]
@tkfu @OYTIS I'm not sure how to resolve this. I can only point out that right now there are two redundant(?), possibly error-prone mechanisms to specify HW IDs. Maybe a good discussion to have at the meeting this Friday, but I will be unavailable then.

**Comment by trishankatdatadog** [comment]
@awwad #74

**Comment by trishankatdatadog** [comment]
Also related to #91

**Comment by trishankatdatadog** [comment]
Closing because we decided to support HW IDs in both delegations and custom targets metadata

For two reasons: (1) backwards-compatibility, and (2) different implementors may wish to use one or both of them

**Pull request closed without merging**
