### PR TITLE
clarifying signature scope

### PR DESCRIPTION
**Pull request by JustinCappos**
This is in response to @trishankatdatadog's observation that the spec is imprecise.

### CODE REVIEW

**Comment by JustinCappos** [comment]
ready for review again @trishankatdatadog.  If this isn't clearer, can you please suggest text?

**Comment by trishankatdatadog** [comment]
@JustinCappos Ok, I have to jump into a meeting, but let me take a crack at it soon

**Comment by trishankatdatadog** [comment]
@JustinCappos Please take a look 👀 

I think this alone should go a long way towards making sure that public keys are properly specified and signed over

I want to take a look at the rest of the metadata syntax later, because I just don't have the time right now

Having said this, we should be good to send out the draft, with the caveat that we're reviewing the metadata specification

**Comment by JustinCappos** [comment]
I'm confused now.  Haven't you moved the signature so that it no longer covers the signing algorithm, signature scheme, key, etc.?   Isn't this the problem that the change was meant to address?

**Comment by JustinCappos** [comment]
@trishankatdatadog Ready for your review again...

**Comment by trishankatdatadog** [comment]
@JustinCappos Sorry for the delay, just saw this. Have to jump into a meeting followed by lunch, but will endeavor to review ASAP... 👀

**Comment by JustinCappos** [comment]
I'm going to make some changes to cause the text to once again define what
an identifier of a key is.  I think the current text also lets the
implementer avoid signing the algorithm type, etc. so long as they are not
in the payload.  Using something like the keyid isn't mandatory but this
makes it seems this way.

Let me readd text that clarifies these points.

**Comment by JustinCappos** [comment]
Okay, I think I got it this time!  

@trishankatdatadog Do you agree?

**Comment by trishankatdatadog** [comment]
Much better now, thanks @JustinCappos!

I think we've solved a major problem with the spec, but we should ask others whether it is as clear to them as it is to us. Really, the best way to test this is to ask someone who has never seen the spec before to implement it.

I will also add the caveat that I haven't looked over the specification for the rest of the metadata syntax / data structures, but this goes a long way.

**Pull request merged**
