### PR TITLE
modifying the use of the word conformant

### PR DESCRIPTION
**Pull request by jhdalek55**
Per our discussion at the 8/2/22 Uptane Standards meeting, I have added a bit of text to the introduction to define the word conformant. I was going to elaborate a bit more on this topic, but I think this is probably sufficient. Note that I wasn't sure how to site the sources of the definition as it is mentioned in https://www.nist.gov/itl/ssd/information-systems-group/what-thing-called-conformance but the actual citation references the ISO guide noted in the text...which is behind a pay wall.

### CODE REVIEW

**Comment by iramcdonald** [comment]
Hi Lois,

I just looked at the file changes you proposed.  Here are some thoughts
about
modifying that text, *without* requiring access behind an ISO paywall.

The free and open ISO Online Browsing Platform (https://www.iso.org/obp/ui)
cites ISO/IEC 13210:1999 Information Technology to define a "conformance
requirement".

So I suggest replacing the first two sentences of your paragraph with the
following text:

"These instructions specify the set of *requirements* necessary for
*specific*
ECU *implementations* *to** satisfy all conformance requirements of* the
Uptane Standard.  ISO/IEC 13210:1999 Information Technology, as cited in
the ISO Online Browsing Platform (https://www.iso.org/obp/ui) defines a
"conformance requirement" as:

"A requirement stated in a *base standard* that identifies a specific
requirement
in a finite, measurable, and unambiguous manner. A *conformance requirement*
by itself or in conjunction with other conformance requirements corresponds
to
an *assertion.*"

And then continue with the third and following original sentences in your
proposed change.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@trishankkarthik @tkfu @mnm678 can we get reviews/suggestions and/or approvals?

**Review by mnm678 — APPROVED** [review]

**Comment by jhdalek55** [comment]
One for review please so we can merge.

**Review by hexsecs — APPROVED** [review]
Looks good to me.

**Comment by iramcdonald** [comment]
Hi Lois,

Did you see my reply with specific suggested revised text and *open* ISO
reference
on Tuesday?  I haven't seen any further traffic on this one.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Pull request merged**
