### PR TITLE
Added profile description

### PR DESCRIPTION
**Pull request by mnm678**
As mentioned in #73, this pr adds a description of profiles to the standard. Additionally, it describes when an implementer may wish to use a profile.

### CODE REVIEW

**Comment by jhdalek55** [comment]
Great. I'll have a look before I leave today. Thanks.

Lois

**Comment by jhdalek55** [comment]
Marina...I made two small changes and one suggestion on your PR. I don't
want to merge the change till you look at at it.

Thanks.

**Comment by mnm678** [comment]
Thanks Lois, it looks good to me. I made the suggested edit as well.

**Comment by jhdalek55** [comment]
Ok. I'm fine with it then.

**Comment by jhdalek55** [comment]
So with this, can we close issue #73?

Lois

**Comment by tkfu** [comment]
I wouldn't close the issue until we have a clear and documented place/process for submitting profiles, and at least one example.

**Comment by jhdalek55** [comment]
Ok. Fair enough.

Lois

**Pull request merged**
