### PR TITLE
adding stipulation about changes on the repo

### PR DESCRIPTION
**Pull request by jhdalek55**
At the July 20 Standards meeting it was agreed that changes can be made as needed in the Standard, and do not have to wait a version is released. To clarify that the repository version of the Standard will sometimes contain different content from the numbered releases, I added some wording at the top of this page. Suggestions/modifications welcomed.

We will need to update some of the other text here, including the "existing documentation." Will we add V.1.2.0 above V.1.1.0 or delete 1.1.0?

### CODE REVIEW

**Review by pattivacek — APPROVED** [review]
> Will we add V.1.2.0 above V.1.1.0 or delete 1.1.0?

In this location, I think it's fine to just link to the latest. There are probably other places where it might be better to list all the versions.

**Comment by jhdalek55** [comment]
Can we get one more approval and then merge this?

**Review by mnm678 — APPROVED** [review]

**Comment by jhdalek55** [comment]
can someone with write access merge this?

**Comment by jhdalek55** [comment]
Thanks, Marina.
Lois

**Pull request merged**
