### PR TITLE
Use Docker image for CI on GitHub Package Registry

### PR DESCRIPTION
**Pull request by trishankatdatadog**

### CODE REVIEW

**Comment by jhdalek55** [comment]
Not a review, but a small comment. Our style guide calls for American English spelling, so the word "artefact" needs to be spelled "artifact"

**Comment by trishankatdatadog** [comment]
@jhdalek55 done

**Comment by trishankatdatadog** [comment]
@tkfu comments, pls?

**Comment by jhdalek55** [comment]
Thanks for fixing the "artifacts."

Lois

**Comment by tkfu** [comment]
I don't have access to the package registry yet, so I can't confirm this works. It certainly looks right, though. @trishankatdatadog, did you already push the image?

**Comment by trishankatdatadog** [comment]
@tkfu yes https://github.com/uptane/uptane-standard/packages/26482

**Comment by patrickvacek** [comment]
Unfortunately, the automation failed after I merged it: https://github.com/uptane/uptane-standard/commit/31af6652243bfb6c55e96ad9727f7db73f91f3c4/checks

**Comment by patrickvacek** [comment]
> It might be worthwhile to revert unless GitHub fixes this... want me to send a PR?

I guess? That's annoying. Depends on how long it takes them to fix it and if we get any changes we want to deploy in the meantime.

**Pull request merged**
