### PR TITLE
Improve example hash naming

### PR DESCRIPTION
**Pull request by zabbal**
Better align example SHA names with
https://csrc.nist.gov/projects/hash-functions/nist-policy-on-hash-functions

While at it, also use example from different hash function families to emphasize
the fact that we're not tied to a particular set of algorithms.

### CODE REVIEW

**Comment by zabbal** [comment]
Seems like I can't assign reviewers explicitly so just pinging in the comments: @trishankkarthik you might be interested. Others feel free to review as well of course.

**Comment by iramcdonald** [comment]
Hi Max,

Sorry for the delay.  Explicitly reviewed the file changes and rationale.
I approve!

Stay safe,
- Ira


*Ira McDonald (Musician / Software Architect)Co-Chair - TCG Trusted
Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@zabbal thanks for this. We should probably take a look at the Deployment pages as well and make sure we are consistent.

**Comment by zabbal** [comment]
I've checked deployment-considerations there seems to be nothing related to SHA examples which needs updating there.

**Comment by jhdalek55** [comment]
Thanks for checking, Max.

**Pull request merged**
