### PR TITLE
Update LICENSE to Community Specification License

### PR DESCRIPTION
**Pull request by JustinCappos**
I don't know the right way to fix the text at the bottom of the standard.  Please don't merge until we figure that out.

### CODE REVIEW

**Review by mnm678 — APPROVED** [review]

**Comment by trishankatdatadog** [comment]
> I don't know the right way to fix the text at the bottom of the standard

WDYM?

**Comment by JustinCappos** [comment]
Check the bottom of this:
https://raw.githubusercontent.com/JustinCappos/uptane-standard-licensefix/master/uptane-standard.md

Is this automatically added to the file?  Is this just a comment we should
remove?

**Comment by JustinCappos** [comment]
FYI: other files in our repo should have "SPDX-License-Identifier: Community-Spec-1.0".  The change should also happen for the PUREs repo, but I'll wait for this to be approved, etc. first.

**Review by trishankatdatadog — APPROVED** [review]
The LICENSE update LGTM

**Comment by trishankatdatadog** [comment]
> Check the bottom of this: https://raw.githubusercontent.com/JustinCappos/uptane-standard-licensefix/master/uptane-standard.md Is this automatically added to the file? Is this just a comment we should remove?

IDK but that change isn't part of this PR

**Comment by JustinCappos** [comment]
> > Check the bottom of this: https://raw.githubusercontent.com/JustinCappos/uptane-standard-licensefix/master/uptane-standard.md Is this automatically added to the file? Is this just a comment we should remove?
> 
> IDK but that change isn't part of this PR

Right, I was trying to solicit help / suggestions from someone in the know about this.  It looks like @tkfu was the one who added it.  Jon, can you comment on this?  Should we just change / excise this mention?  Is it autogenerated?

**Comment by hexsecs** [comment]
In order to move to the Community Specification license I believe we need to add some other supplementary files in the repository as well. The License references these. See below...
https://github.com/CommunitySpecification/Community_Specification/tree/main

Here is a good reference of how we can adopt the license.
https://github.com/CommunitySpecification/Community_Specification/blob/main/..Getting%20Started.md

**Pull request merged**
