### PR TITLE
Change should to must for preventing director replay

### PR DESCRIPTION
**Pull request by mnm678**
Solves #202

### CODE REVIEW

**Review by jhdalek55 — COMMENTED** [review]
Thanks @mnm678. A reminder though that we agreed to use SHALL instead of MUST for any mandatory directions.

**Comment by mnm678** [comment]
> Thanks @mnm678. A reminder though that we agreed to use SHALL instead of MUST for any mandatory directions.

Updated. We'll probably want to do a pass of the whole standard for this before we release 2.0.

**Review by jhdalek55 — APPROVED** [review]
This is fine now.

**Comment by jhdalek55** [comment]
@mnm678 you are right. We'll need to check for MUSTs before we finalize the draft. Thanks for taking care of this PR.

**Review by tkfu — APPROVED** [review]

**Pull request merged**
