### PR TITLE
Standardize spelling of "implementer".

### PR DESCRIPTION
**Pull request by patrickvacek**

### CODE REVIEW

**Review by mnm678 — APPROVED** [review]

**Comment by iramcdonald** [comment]
Hi,

Sigh...

OK, this is the US spelling.

But the rest of the world (including all ISO and ITU-T standards) use the
OED
standard spelling of "implementors".

Not worth worrying about, except to be consistent within Uptane Standard
and the
Deployment Best Practices.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by patrickvacek** [comment]
> OK, this is the US spelling. But the rest of the world (including all ISO and ITU-T standards) use the OED standard spelling of "implementors".

Interesting! I've been annoyed with the fact we inconsistently have used both for a while, and Lois recently indicated "implementer" was the agreed-upon spelling for us. And according to this [Google ngram comparison](https://books.google.com/ngrams/graph?content=implementer%3Aeng_us_2012%2Cimplementor%3Aeng_gb_2012%2Cimplementor%3Aeng_us_2012%2Cimplementer%3Aeng_gb_2012&year_start=1900&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cimplementer%3Aeng_us_2012%3B%2Cc0%3B.t1%3B%2Cimplementor%3Aeng_gb_2012%3B%2Cc0%3B.t1%3B%2Cimplementor%3Aeng_us_2012%3B%2Cc0%3B.t1%3B%2Cimplementer%3Aeng_gb_2012%3B%2Cc0#t1%3B%2Cimplementer%3Aeng_us_2012%3B%2Cc0%3B.t1%3B%2Cimplementor%3Aeng_gb_2012%3B%2Cc0%3B.t1%3B%2Cimplementor%3Aeng_us_2012%3B%2Cc0%3B.t1%3B%2Cimplementer%3Aeng_gb_2012%3B%2Cc0), British English speakers also seem to prefer "implementer".

> Not worth worrying about, except to be consistent within Uptane Standard and the Deployment Best Practices.

I opened PRs for both (and the website).

**Comment by jhdalek55** [comment]
Yes. This isn't Britain vs U.S. It's purely a matter of a style change over the last few years.

**Review by jhdalek55 — APPROVED** [review]
Thanks for doing this "clean-up" step, @patrickvacek .

**Pull request merged**
