### PR TITLE
Fixing the phrase ECU key re: Issue #139

### PR DESCRIPTION
**Pull request by jhdalek55**
I changed the text for "ECU keys" in section 5.4.1.1 of the Standard to partially address Issue #139 in Deployment Considerations. This is following up on a suggestion from @hexsecs .

### CODE REVIEW

**Comment by jhdalek55** [comment]
Again, this is a fairly simple change that will be a first step towards resolving Issue #139 on the Deployment page.

**Review by mnm678 — APPROVED** [review]

**Comment by jhdalek55** [comment]
Asking again for one more approval so we can merge this and be a step closer to resolving the Deployment page issue on  clarifying keys used on ECUs.

**Comment by iramcdonald** [comment]
Hi Lois,

I approve.

It's an improvement and we should *later* (v2.2) do a bit more in
Deployment and Standard
to be a little crisper at times, IMO.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Can someone with privileges merge this?

**Pull request merged**
