### PR TITLE
Clarify connectivity assumptions. Fixes #30

### LINKED ISSUE #30: Ambigious Assumption: "Vehicles have regular connectivity established."
In Section 3.2.1 (https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.3.2.1) of the standard, the first assumption presented is that:

> "Vehicles have regular connectivity established. The common scenario is cellular connectivity, but Uptane could also be applied via other communication channels such as WiFi and even wired connections."

I am worried this is overly ambiguous and may scare away potential implementers. What does "regular connectivity" mean here? Normal?

If so, does Uptane fail to work for vehicles who have subpar connectivity (poor location, limited data plans, etc.)? I'm pretty sure the answer is no, Uptane works fine.

I think the real assumption is more along the lines of: "Vehicles are capable of establishing connectivity".

### PR DESCRIPTION
**Pull request by JosiahOne**
This pull request changes the wording of the connectivity assumption in Section 3.2.1 to resolve my concern in #30.

It also softens the emphasis on cellular technologies, given Ira's comments in the same issue.

### CODE REVIEW

**Comment by iramcdonald** [comment]
Hi Josiah,

This patch looks OK, except for:

ECUs are either directly connected to the communication channel, or
they are indirectly
connected via some sort of gateway. The gateway may not be trusted.

I don't like that unhelpful (for security analysis) "The gateway may not be
trusted."
The entire public Internet, as well as any telecom cellular network, *is*
not trusted.
That's what end-to-end Transport (e.g., TLS) and Application
(object-signature)
security protocols are for.

If you meant specifically a "gateway" within a vehicle network, I suggest
that Uptane
shouldn't talk about those.  Vehicle topology needs to be a black box to
Uptane.

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JosiahOne** [comment]
Hi @iramcdonald,

Thanks. The "...gateway may not be trusted." text was pre-existing, however.

That said, I'm with you in that the text is unhelpful and ambiguous, so I will remove it...

**Comment by JosiahOne** [comment]
I updated the PR. Let me know if you think my edits resolve your comment @iramcdonald 

Also, I need a reviewer for this PR, but can't assign one.

**Comment by iramcdonald** [comment]
Hi,

Thanks Josiah.  Yes, your changes resolved my concerns.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Pull request merged**
