### PR TITLE
Clarify download/verify subsection

### LINKED ISSUE #121: Clarify "download and verify images" language
In "Download and verify images" subsection spec says:
"There may be several different filenames that all refer to the same image binary, as described in {{targets_meta}}. The primary SHALL associate each image binary with each of its possible filenames."

1) I think this should actually refer to #metadata_filename_rules because that's where bit about different names for the same file is actually clarified.

2) The last sentence is rather confusing (might be just my English though) - the way I understand it, it suggest for ECU to obtain for each "acme_firmware.bin" a list of all the names like "aaaa.acme_firmware.bin", "bbbb.acme_firmware.bin" etc where "aaaa" is hash1 (sha256 for example), "bbbb" is hash2 (sha3) and so on.

According to #targets_images_meta the "One or more hashes of the image file, along with the hashing function used" is part of the list obtained from the targets role.

So if the intention is to make sure ECU checks every hash of a given firmware (and not just a single one) it's better to state this explicitly and refere to #targets_images_meta. If not than it deserves clarification.

There might be more hashes of a given image in the repository than supplied via targets role so requesting "each of its possible filenames" seems too broad.

### PR DESCRIPTION
**Pull request by zabbal**
Fixes #121.

Signed-off-by: Max <max.suraev@here.com>

### CODE REVIEW

**Comment by zabbal** [comment]
Would be nice to have some native speaker looking over this. Feel free to fix as you see fit.

**Comment by iramcdonald** [comment]
Hi Max,

The deadline for any pull requests for Uptane Standard v1.0 was 14 June
2019.

I appreciate your contributions, but note that they will go into some
future version
of Uptane Standard *after* the Uptane project transitions to Linux
Foundation.

I'm also too busy for the next three months to read any new Uptane text -
sorry.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by iramcdonald** [comment]
Hi Max,

CORRECTION - Per Trishank's note earlier today, any PR or Issue turned
into a PR that is resolved by this Wednesday *will* go into Uptane v1.

My apologies for losing track of our moving target for closure.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by zabbal** [comment]
I'm fine either way - the point is to make it easier for implementors. Whether the clarification is in 1.0 directly or in the issue tracker is a matter of convenience, nothing more :)

**Comment by jhdalek55** [comment]
This is a very small change so I think we should be able to be incorporate it if someone outside of Max's organization can give it a look. I noticed a small typo in line 724 (it should be "then" instead of "than" because this is sequence of events, rather than comparison.) So that's my grammatical 2 cents, but does anyone have a problem with the change from a technical standpoint?

Thanks.

**Comment by iramcdonald** [comment]
Hi,

With Lois' comment about "than" to "then", looks fine to me.

Can someone please merge this one?

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Pull request merged**
